package com.liuchang.momohongbao.model.db;

import com.liuchang.momohongbao.model.bean.Hongbao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hongbaoDaoConfig;

    private final HongbaoDao hongbaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hongbaoDaoConfig = daoConfigMap.get(HongbaoDao.class).clone();
        hongbaoDaoConfig.initIdentityScope(type);

        hongbaoDao = new HongbaoDao(hongbaoDaoConfig, this);

        registerDao(Hongbao.class, hongbaoDao);
    }

    public void clear() {
        hongbaoDaoConfig.clearIdentityScope();
    }

    public HongbaoDao getHongbaoDao() {
        return hongbaoDao;
    }

}
